@hostname = localhost
@port = 3333
@host = {{hostname}}:{{port}}
@contentType = application/json

### POST /categories
POST http://{{host}}/categories HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "John Fodase"
}


### POST /users
POST http://{{host}}/users HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "John",
    "email": "michael@michael.com",
    "password": "1234567",
    "uriImage": "teste.com"
}

### GET Users
GET http://{{host}}/users HTTP/1.1

### POST /users
POST http://{{host}}/products HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "John",
    "email": "michael@michael.com",
    "password": "1234567",
    "uriImage": "teste.com"
}
